version: '3.8'

services:
  type_node:
    image: naren200/type_node:v1
    container_name: type_node
    devices:
      - /dev/snd:/dev/snd
    network_mode: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    runtime: nvidia 
    volumes:
      - "${LOCAL_WS}/.:/root/type_ws/"
      - "./transcripts:/app/output"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - CAPTURE_DEVICE=${CAPTURE_DEVICE}
    privileged: true
    stdin_open: true
    tty: true
